export const Translations = {
  EmployeeID: 'Код сотрудника',
  FullName: 'ФИО',
  Age: 'Возраст',
  Gender: 'Пол',
  Address: 'Адрес',
  Phone: 'Телефон',
  Passportserial: 'Серия паспорта',
  Passportnumber: 'Номер паспорта',
  Passportdate: 'Дата выдачи паспорта',
  PositionID: 'Код Должности',
  createdAt: 'Дата создания',
  updatedAt: 'Дата обновления',
  PositionName: 'Должность',
  PositionSalary: 'Зарплата ₽',
  PositionDuties: 'Обязанности',
  PositionRequirements: 'Требования',
  PlaneID: 'Код самолета',
  Mark: 'Марка',
  Capacity: 'Вместимость',
  Tonnage: 'Грузоподъемность',
  TypeID: 'Код типа',
  Characteristic: 'Характеристика',
  ReleaseDate: 'Дата выпуска',
  FlyingHours: 'Часы полета',
  LastRepairDate: 'Дата последнего ремонта',
  PlaneTypeName: 'Тип',
  PlaneTypeTarget: 'Назначение',
  PlaneTypeConstraint: 'Ограничения',
  AssignedEmployeeFullName: 'ФИО',
  AssignedEmployeePhone: 'Телефон',
  AssignedEmployeePositionID: 'Код должности',
  CrewID: 'Код экипажа',
  EmployeeID_1: 'Код сотрудника 1',
  EmployeeID_2: 'Код сотрудника 2',
  EmployeeID_3: 'Код сотрудника 3',
  CreatedAt: 'Дата создания',
  UpdatedAt: 'Дата обновления',
  Employee_1FullName: 'ФИО сотрудника 1',
  Employee_1Phone: 'Телефон сотрудника 1',
  Employee_1PositionID: 'Код должности 1 сотрудника',
  Employee_2FullName: 'ФИО сотрудника 2',
  Employee_2Phone: 'Телефон сотрудника 2',
  Employee_2PositionID: 'Код должности 2 сотрудника',
  Employee_3FullName: 'ФИО сотрудника 3',
  Employee_3Phone: 'Телефон сотрудника 3',
  Employee_3PositionID: 'Код должности 3 сотрудника',
  FlightID: 'Код Рейса',
  Date: 'Дата',
  Time: 'Время',
  From: 'Откуда',
  To: 'Куда',
  FlightTime: 'Время полета',
  PlaneMark: 'Марка самолета',
  PlaneTypeID: 'Код типа самолета',
  PlaneFlyingHours: 'Часы полета самолета',
  CrewFlyingHours: 'Часы полета экипажа',
  CrewEmployeeID_1: 'Код сотрудника 1',
  CrewEmployeeID_2: 'Код сотрудника 2',
  CrewEmployeeID_3: 'Код сотрудника 3',
  TicketID: 'Код билета',
  Seat: 'Место',
  Price: 'Цена',
  FlightDate: 'Дата',
  FlightFrom: 'Откуда',
  FlightTo: 'Куда',
  FlightFlightTime: 'Время полета',
  Name: 'Название',
  Salary: 'Зарплата',
  Duties: 'Обязанности',
  Requirements: 'Требования',
  Target: 'Назначение',
  Employee: 'Сотрудника',
  Position: 'Должность',
  Plane: 'Самолет',
  PlaneType: 'Тип самолета',
  Crew: 'Экпипаж',
  Flight: 'Рейс',
  Ticket: 'Билет',
  Constraint: 'Ограничения',
};
